let students = [
    { id: 1, name: "Jack", course: "React", grade: "A", city: "London" },
    { id: 2, name: "Tim", course: "Node", grade: "B", city: "Paris" },
    { id: 3, name: "Anna", course: "JS", grade: "C", city: "New York" },
    { id: 4, name: "Bob", course: "Angular", grade: "D", city: "Boston" },
    { id: 5, name: "Mary", course: "React", grade: "A", city: "Miami" },
    { id: 6, name: "steve", course: "Node", grade: "B", city: "San Diego" },
    { id: 7, name: "Kathy", course: "JS", grade: "C", city: "Las Vegas" },
    { id: 8, name: "Vivian", course: "JS", grade: "C", city: "Orlando" },
    { id: 9, name: "Edwards", course: "React", grade: "A", city: "San Antonio" },
    { id: 10, name: "Geroge", course: "Angular", grade: "D", city: "Austin" },
    { id: 11, name: "Sam", course: "React", grade: "A", city: "Denver" },
    { id: 12, name: "Amy", course: "Node", grade: "B", city: "Honolulu" },
    { id: 13, name: "Jill", course: "JS", grade: "C", city: "New Orleans" },
    { id: 14, name: "Duke", course: "React", grade: "A", city: "Filadélfia" },
    { id: 15, name: "Anita", course: "React", grade: "A", city: "Indianápolis" },
    { id: 16, name: "Mike", course: "Angular", grade: "D", city: "Columbus" },
    { id: 17, name: "Teddy", course: "React", grade: "A", city: "Atlanta" },
    { id: 18, name: "Charles", course: "React", grade: "A", city: "Charlote" },
    { id: 19, name: "Evlyn", course: "JS", grade: "C", city: "Dallas" },
    { id: 20, name: "Hilary", course: "Android", grade: "E", city: "Houston" },
    { id: 21, name: "Ashley", course: "JS", grade: "C", city: "Phoenix" },
    { id: 22, name: "Sheldon", course: "React", grade: "A", city: "Memphis" },
    { id: 23, name: "Emma", course: "React", grade: "A", city: "Jacksonville" },
    { id: 24, name: "Scarlett", course: "Android", grade: "E", city: "Detroit" },
    { id: 25, name: "Stephany", course: "Android", grade: "E", city: "Oklahoma City" },
    { id: 26, name: "Abigail", course: "React", grade: "A", city: "Cleveland" },
    { id: 27, name: "Mila", course: "React", grade: "A", city: "Pitsburgo" },
]

module.exports = {studentsData: students} // ou module.exports.studentsData = students
